### ISSUE TITLE
Can you support Yml files?

### ISSUE THREAD

**Issue by BD-AliceHeiBai** [blaxxun-boop/PassivePowers#8]
_你好！
我将您的Mod翻译为了中文
但是由于这个MOD没有Yml。所以我只能覆盖Dll文件
我无法分享我的翻译，这会导致版权问题
您可以支持Yml文件吗？_

**Hi!
I translated your Mod into Chinese
But since this MOD doesn't have Yml. So I can only overwrite Dll files
I can't share my translations, it causes copyright issues
Can you support Yml files?**

![Boss](https://user-images.githubusercontent.com/110221837/213456959-b4bf090e-c854-4f77-aae7-1804361a9bbb.png)

**Comment by blaxxun-boop** [comment]
With v1.0.9, you can now drop a file called PassivePowers.Chinese.yml into your config folder. Copy over the English translations from https://github.com/blaxxun-boop/PassivePowers/blob/master/PassivePowers/translations/English.yml and then translate them.

**Comment by BD-AliceHeiBai** [comment]
很抱歉
D:\SteamLibrary\steamapps\common\Valheim\BepInEx\config\PassivePowers.Chinese.yml 
并没有正确的生效
在Dll资源添加PassivePowers.translations.Chinese.yml是正常的，这可能是个Bug？

---------------------------------------------
I'm sorry
`D:\SteamLibrary\steamapps\common\Valheim\BepInEx\config\PassivePowers.Chinese.yml `
It doesn't take effect correctly :(
But in Dll resource add `PassivePowers.translations.Chinese.yml`is normal,
maybe this is a bug?

**Comment by blaxxun-boop** [comment]
Works perfectly fine. If you are using R2 or the Thunderstore Mod Manager, please note that your config folder is inside of your profile folder.
Settings -> Locations -> Browse Profile Folder.
