### ISSUE TITLE
Incompatible with Valheim Plus

### ISSUE THREAD

**Issue by XarisZ** [blaxxun-boop/PassivePowers#9]
I was looking into the BepInEx and i saw this 
[Error  :   BepInEx] Could not load [Dual Wield 1.0.6] because it is incompatible with: org.bepinex.plugins.valheim_plus

**Comment by blaxxun-boop** [comment]
Yes, that is on purpose.

Read https://github.com/blaxxun-boop/PassivePowers/issues/5 for more information.

**Comment by XarisZ** [comment]
there is no plan to patch these mods to work together?

**Comment by blaxxun-boop** [comment]
No, not a single mod of mine will ever work with Valheim Plus again.
Same goes for quite a few other modders.
